### ISSUE TITLE
_pickle.UnpicklingError: invalid load key, '\xff'.

### ISSUE THREAD

**Issue by nickyvdz-art** [czczup/URST#1]
no problems, fixed. - thank you so very much for this, this is truly excellent, what a package!

**Comment by nickyvdz-art** [comment]
(Wang) C:\Users\Bob\URST\Johnson2016Perceptual>python test.py --content C:\Users\Bob\Desktop\ds.jpg --model C:\Users\Bob\Desktop\dsstyle.jpg --URST
Namespace(URST=True, content='C:\\Users\\Bob\\Desktop\\ds.jpg', device='cuda', model='C:\\Users\\Bob\\Desktop\\dsstyle.jpg', outf='output', padding=32, patch_size=1000, test_speed=False, thumb_size=1024)
Traceback (most recent call last):
  File "test.py", line 76, in <module>
    checkpoint = torch.load(args.model)
  File "C:\Users\Bob\anaconda3\envs\Wang\lib\site-packages\torch\serialization.py", line 387, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "C:\Users\Bob\anaconda3\envs\Wang\lib\site-packages\torch\serialization.py", line 564, in _load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '\xff'.

this im having trouble working out though?

**Comment by czczup** [comment]
> (Wang) C:\Users\Bob\URST\Johnson2016Perceptual>python test.py --content C:\Users\Bob\Desktop\ds.jpg --model C:\Users\Bob\Desktop\dsstyle.jpg --URST
> Namespace(URST=True, content='C:\Users\Bob\Desktop\ds.jpg', device='cuda', model='C:\Users\Bob\Desktop\dsstyle.jpg', outf='output', padding=32, patch_size=1000, test_speed=False, thumb_size=1024)
> Traceback (most recent call last):
> File "test.py", line 76, in
> checkpoint = torch.load(args.model)
> File "C:\Users\Bob\anaconda3\envs\Wang\lib\site-packages\torch\serialization.py", line 387, in load
> return _load(f, map_location, pickle_module, **pickle_load_args)
> File "C:\Users\Bob\anaconda3\envs\Wang\lib\site-packages\torch\serialization.py", line 564, in _load
> magic_number = pickle_module.load(f, **pickle_load_args)
> _pickle.UnpicklingError: invalid load key, '\xff'.
> 
> this im having trouble working out though?

Hi, Johnson2016Perceptual is a style-specific style transfer method, that is, it requires training a model for each style. So this method has no `--style` option. The `--model` option requires a `.pth` model instead of an image.

**Comment by nickyvdz-art** [comment]
apologies for my misunderstanding, I must have previously used different variation of Johnson2016Perceptual - thanks for getting back to me so soon

again, I am really grateful for this, thank you for your work / efforts
