### ISSUE TITLE
Li2017 Universal - unhashable type list

### ISSUE THREAD

**Issue by nickyvdz-art** [czczup/URST#2]
(Wang) C:\Users\Bob\URST\Li2017Universal>python test.py --content c:\users\bob\desktop\ds.jpg --style c:\users\bob\desktop\dsstyle.jpg --URST
Traceback (most recent call last):
  File "test.py", line 166, in <module>
    wct = WCT(args).to(device)
  File "C:\Users\Bob\URST\Li2017Universal\util.py", line 16, in __init__
    vgg1 = torchfile.load(args.vgg1)
  File "C:\Users\Bob\anaconda3\envs\Wang\lib\site-packages\torchfile.py", line 424, in load
    return reader.read_obj()
  File "C:\Users\Bob\anaconda3\envs\Wang\lib\site-packages\torchfile.py", line 370, in read_obj
    obj._obj = self.read_obj()
  File "C:\Users\Bob\anaconda3\envs\Wang\lib\site-packages\torchfile.py", line 385, in read_obj
    k = self.read_obj()
  File "C:\Users\Bob\anaconda3\envs\Wang\lib\site-packages\torchfile.py", line 386, in read_obj
    v = self.read_obj()
  File "C:\Users\Bob\anaconda3\envs\Wang\lib\site-packages\torchfile.py", line 370, in read_obj
    obj._obj = self.read_obj()
  File "C:\Users\Bob\anaconda3\envs\Wang\lib\site-packages\torchfile.py", line 387, in read_obj
    obj[k] = v
TypeError: unhashable type: 'list'

**Comment by czczup** [comment]
> (Wang) C:\Users\Bob\URST\Li2017Universal>python test.py --content c:\users\bob\desktop\ds.jpg --style c:\users\bob\desktop\dsstyle.jpg --URST
> Traceback (most recent call last):
> File "test.py", line 166, in
> wct = WCT(args).to(device)
> File "C:\Users\Bob\URST\Li2017Universal\util.py", line 16, in **init**
> vgg1 = torchfile.load(args.vgg1)
> File "C:\Users\Bob\anaconda3\envs\Wang\lib\site-packages\torchfile.py", line 424, in load
> return reader.read_obj()
> File "C:\Users\Bob\anaconda3\envs\Wang\lib\site-packages\torchfile.py", line 370, in read_obj
> obj._obj = self.read_obj()
> File "C:\Users\Bob\anaconda3\envs\Wang\lib\site-packages\torchfile.py", line 385, in read_obj
> k = self.read_obj()
> File "C:\Users\Bob\anaconda3\envs\Wang\lib\site-packages\torchfile.py", line 386, in read_obj
> v = self.read_obj()
> File "C:\Users\Bob\anaconda3\envs\Wang\lib\site-packages\torchfile.py", line 370, in read_obj
> obj._obj = self.read_obj()
> File "C:\Users\Bob\anaconda3\envs\Wang\lib\site-packages\torchfile.py", line 387, in read_obj
> obj[k] = v
> TypeError: unhashable type: 'list'

I am not sure if this is due to the version of torchfile, my torchfile is `0.1.0`.

**Comment by nickyvdz-art** [comment]
it also is 0.1.0

**Comment by czczup** [comment]
> it also is 0.1.0

You can try this:
https://github.com/bshillingford/python-torchfile/issues/12

**Comment by nickyvdz-art** [comment]
ok, maybe a windows problem; 

i have clear linux also, just currently in windows poking around; 

im assuming you have no problems on Linux?

**Comment by czczup** [comment]
yes, it works fine on Linux.
