### ISSUE TITLE
TIN application

### ISSUE THREAD

**Issue by nickyvdz-art** [czczup/URST#4]
Hi,

Sorry to bother again - lets say; roughly, forgive my expression; 

using cysmith neural transfer (LGBFS optimizer), I process 4 x (500 x 500) slices of a lets say 2000 x 2000 pixel image-A, and I process one total picture thumbnail of 500 x 500 pixel of image-A (i suppose, downsampled from the original 2000 x 2000 image-A)

now, using your TIN method; 

would I be able to 'stitch' these back together and then get rid of the 'stitch' area problems?

is it possible to string together or isolate some code as to achieve something like this? 

thanks again for your time and consideration

- apologies if ive missed or misunderstood something from your method / paper article

**Comment by czczup** [comment]
I'm sorry, our TIN is not suitable for this method. The premise of TIN application is that there must have IN or IW layer in the style transfer network. The [cysmith neural transfer](https://github.com/cysmith/neural-style-tf) method you mentioned is an implementation of [Gatys et al. 's algorithm](http://www.cv-foundation.org/openaccess/content_cvpr_2016/papers/Gatys_Image_Style_Transfer_CVPR_2016_paper.pdf), which is an iteration-based method. That is to say, there is no IN/IW-based feed-forward network for style transfer in this method.
